### ISSUE TITLE
Tracker for using trybuild fork

### ISSUE THREAD

**Issue by LecrisUT** [taiki-e/derive_utils#48]
Hi, I am trying to package your project for Fedora due to a dependency chain

I have noticed that you are using a fork of `trybuild`, is there any tracker for how long you will be using the fork or the PR related to it?

**Comment by taiki-e** [comment]
Could you tell me what kind of problem the use of forks in dev-dependencies would cause?

pin-project-lite that uses trybuild fork in the same way seems to be packaged without asking me the same question. https://packages.fedoraproject.org/pkgs/rust-pin-project-lite/

> is there any tracker for how long you will be using the fork or the PR related to it?

I have no plans to stop using the fork at this time. I need to maintain the fork for pin-project-lite's use case anyway and differences in behavior between projects can be annoying. Also, I don't think the changes I have introduced will be accepted upstream.

**Comment by LecrisUT** [comment]
When packaging for Fedora we redistribute the crates in crates.io, sometimes with some downstream changes, e.g. using Fedora maintained system packages. Thus we have to package each project independently, and we don't package individual forks.

`pin-project-lite` works because the tests are not being compiled or run. But that is rather unfortunate and we do try to get as much of your tests run as possible. I am also disabling such tests for this, but it would be nice if we didn't have to do that.

One option of course is if you forked `trybuild` and packaged it for crates.io

**Comment by taiki-e** [comment]
Thanks for the explanation.

This crate cannot be tested without the private test helper that depends on this crate, so the tests cannot be run with just the code published on crates.io anyway. So I believe it would not be helpful to remove the fork here.

https://github.com/taiki-e/derive_utils/blob/63cc68e55911ae95bd976427f2e0d11aa5e0473e/Cargo.toml#L35-L36

**Comment by taiki-e** [comment]
Given that there are crates cannot include versions in dev-dependencies due to the cargo limitations (i.e., dev-dependencies are stripped at publish), depend on subcrates to test (subcrates are not included in the published crate), and exclude tests from crates.io, I think the way to reliably test more things here would be to clone the repository based on the hash included in .cargo_vcs_info.json from crates.io and test it, rather than the downloaded source from crates.io and test it. (see also https://github.com/rust-lang/futures-rs/issues/2025, https://users.rust-lang.org/t/what-to-include-when-publishing-a-crate/51992, etc.)

I'm going to close this issue because this crate is a case of "crates depend on subcrates to test".

**Comment by LecrisUT** [comment]
We cannot do the cloning approach. When rust packages are being built in Fedora, *all* dependencies are being built with cargo pulling in the dependencies from crates.io, but instead of directing to crates.io it directs to the Fedora repositories.

The published `Cargo.toml` in the `derive_utils` crate has the git repo package dependencies removed so the first issue is that even if you downloaded the crate and extracted it, you would not be able to run the tests because the metadata is missing.

However if you were to publish your fork as `trybuild-by-taiki-e` or however you would want to name it, then the issue would be resolved because the dependency would be a simple crate dependency. And there are precedence of that, most recenty I had with `tiny-bip39`.

But looking at your commits in `trybuild`, I don't quite see why it would be soo controversial that it couldn't be integrated in some form.

**Comment by taiki-e** [comment]
> However if you were to publish your fork as trybuild-by-taiki-e or however you would want to name it, then the issue would be resolved because the dependency would be a simple crate dependency. And there are precedence of that, most recenty I had with tiny-bip39.

IIUC the actual problem in running the tests is the test helper crate mentioned in https://github.com/taiki-e/derive_utils/issues/48#issuecomment-2438127817 (subcrates are not included in the published crate). Even if patches to trybuild were upstreamed or published as another crate, the problem would not be resolved.

**Comment by LecrisUT** [comment]
The test that I am trying to build are those in `tests/*`:
https://github.com/taiki-e/derive_utils/blob/82d0c4ec20d63aa822d9cadf3d40cef5fa6d668a/tests/compiletest.rs#L8

**Comment by taiki-e** [comment]
Yeah, they depend on example_derive:

https://github.com/taiki-e/derive_utils/blob/82d0c4ec20d63aa822d9cadf3d40cef5fa6d668a/tests/ui/variant.rs#L3

**Comment by LecrisUT** [comment]
Argh... Ok, that's fair I guess :(. There could probably be ways to inline the `Cargo.toml`, but haven't looked through enough to find a reference
